### ISSUE TITLE
Does this mean PTB4.0 may support/be based on Vulkan?

### ISSUE THREAD

**Issue by hyiltiz** [kleinerm/jesse-cube#1]
How awesome would that be?

**Comment by kleinerm** [comment]
Why would it be awesome? Doing that would be the biggest possible pointless waste of work time i could imagine, and a backwards compatibility nightmare.

I don't plan to have a PTB 4.0 ever. Unless it would be a completely backwards incompatible release that would break every PTB script ever written. I can't think of a feature or reason important enough to even bump to PTB 3.1.

We will use Vulkan in a very limited fashion on Linux and Windows on some graphics cards purely as a display backend for some very special purpose use cases that currently can't be done with OpenGL. Most stuff will continue to not use Vulkan at all. But even for those special case applications, 98% of all work will continue to be done in OpenGL.
